# Generated by Django 4.0.2 on 2022-02-16 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.IntegerField()),
                ('referee', models.IntegerField()),
            ],
        ),
    ]
