# Generated by Django 4.0.2 on 2022-04-11 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.IntegerField()),
                ('referee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Referrer_referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_id', models.CharField(blank=True, max_length=9)),
                ('referee_id', models.CharField(blank=True, max_length=9)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
    ]
