# Generated by Django 4.0.2 on 2022-02-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referrer_referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_id', models.CharField(blank=True, max_length=9)),
                ('referee_id', models.CharField(blank=True, max_length=9)),
                ('level', models.BooleanField(default=False)),
            ],
        ),
    ]
