# Generated by Django 4.0.2 on 2022-02-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_alter_credit_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
