# Generated by Django 4.0.2 on 2022-02-22 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_delete_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.IntegerField()),
                ('referee', models.IntegerField()),
            ],
        ),
    ]
