# Generated by Django 4.0.2 on 2022-03-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrer_referee',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
