# Generated by Django 4.0.2 on 2022-02-09 22:12

from django.db import migrations, models
import g4growth.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cover_img', models.FileField(blank=True, null=True, storage=g4growth.storage_backends.MediaStorage, upload_to='')),
                ('file', models.FileField(blank=True, null=True, storage=g4growth.storage_backends.MediaStorage, upload_to='')),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('deleted', 'DELETED')], default='active', max_length=8)),
            ],
        ),
    ]
