# Generated by Django 4.0.2 on 2022-02-11 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import g4growth.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, storage=g4growth.storage_backends.MediaStorage, upload_to='')),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('deleted', 'DELETED')], default='active', max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='file',
        ),
        migrations.CreateModel(
            name='VideoUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_purchased', models.DateTimeField(auto_now_add=True)),
                ('is_watched', models.BooleanField(default=False)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.videos')),
            ],
        ),
        migrations.AddField(
            model_name='videos',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
