# Generated by Django 4.0.2 on 2022-02-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_videos_remove_course_file_videouser_videos_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
