# Generated by Django 4.0.2 on 2022-02-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_videos_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_videos',
            field=models.IntegerField(default=0),
        ),
    ]
