# Generated by Django 4.0.2 on 2022-02-14 07:18

from django.db import migrations, models
import g4growth.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_total_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_img',
            field=models.FileField(blank=True, null=True, storage=g4growth.storage_backends.PublicMediaStorage, upload_to=''),
        ),
    ]
