# Generated by Django 4.0.2 on 2022-02-16 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import g4growth.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_alter_course_cover_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_purchased', models.DateTimeField(auto_now_add=True)),
                ('percentage', models.IntegerField(default=0)),
                ('payment_ss', models.ImageField(blank=True, null=True, storage=g4growth.storage_backends.PublicMediaStorage, upload_to='')),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.video')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
