# Generated by Django 4.0.2 on 2022-04-11 05:45

from django.db import migrations, models
import g4growth.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phoneno', models.BigIntegerField(unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('profile_img', models.ImageField(blank=True, storage=g4growth.storage_backends.PublicMediaStorage2, upload_to='')),
                ('referral_id', models.CharField(blank=True, max_length=9, unique=True)),
                ('referrer_id', models.CharField(blank=True, max_length=9)),
                ('total_credit', models.IntegerField(default=0)),
                ('total_debit', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.IntegerField(blank=True, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('otp_validity', models.DateTimeField(blank=True, null=True)),
                ('is_logged', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
