# Generated by Django 4.0.2 on 2022-02-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phoneno', models.IntegerField(unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('profile_img', models.ImageField(blank=True, upload_to='profile_pics')),
                ('referral_id', models.IntegerField()),
                ('referrer_id', models.IntegerField()),
                ('total_credit', models.IntegerField(default=0)),
                ('total_debit', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_no', models.IntegerField()),
                ('ifsc_code', models.CharField(max_length=100)),
                ('otp', models.IntegerField()),
                ('otp_validity', models.DateTimeField()),
                ('is_logged', models.BooleanField(default=True)),
                ('is_banned', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
