# Generated by Django 4.0.2 on 2022-02-14 18:02

from django.db import migrations, models
import g4growth.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_name_alter_user_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, storage=g4growth.storage_backends.PublicMediaStorage2, upload_to=''),
        ),
    ]
