# Generated by Django 4.0.2 on 2022-02-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_id',
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='referrer_id',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
